class AddIndexes < ActiveRecord::Migration[6.1]
  def change
#=begin    
add_index :actions, :created_by_id
add_index :attachments, :created_by_id
add_index :attachments, :organization_id
add_index :attachments, :updated_by_id
add_index :batch_attachments, :attachment_id
add_index :batch_attachments, :batch_id
add_index :batches, :created_by_id
add_index :batches, :previous_state_changed_by_id
add_index :batches, :product_id
add_index :batches, :state_changed_by_id
add_index :batches, :updated_by_id
add_index :billing_rates, :created_by_id
add_index :billing_rates, :updated_by_id
add_index :brands, :producer_id
#=end
#add_index :certificates [:product_id, :certifier_id], :unique => true#, :name => 'index_certificates_on_product_id_and_certifier_id'
add_index :certificates, :unique_id
add_index :certification_letters, :certifier_id
add_index :certification_letters, :company_id
add_index :certification_letters, :created_by_id
add_index :certification_letters, :producer_id
add_index :certification_letters, :updated_by_id
add_index :cities, :country_id
add_index :cities, :dma_id
add_index :cities, :region_id
add_index :company_brands, :brand_id
add_index :company_brands, :company_id
add_index :contacts, :created_by_id
add_index :contacts, :entered_by_company_id
add_index :contacts, :organization_id
add_index :contacts, :updated_by_id
add_index :copack_relationship_attachments, :attachment_id
add_index :copack_relationship_attachments, :copack_relationship_id
#add_index "generated_certificates", ["certificate_id"], :name => "index_generated_certificates_on_certificate_id", :unique => true
add_index :generated_certificates, :company_id
add_index :generated_certificates, :created_by_id
add_index :generated_certificates, :updated_by_id
add_index :ingredient_attachments, :attachment_id
add_index :ingredient_attachments, :ingredient_id
add_index :ingredient_groups, :company_id
add_index :ingredient_plants, :ingredient_id
add_index :ingredient_plants, :plant_id
add_index :ingredients, :company_id
add_index :ingredients, :created_by_id
add_index :ingredients, :ingredient_group_id
add_index :ingredients, :previous_id
add_index :ingredients, :previous_state_changed_by_id
add_index :ingredients, :state_changed_by_id
add_index :ingredients, :updated_by_id
add_index :inspected_event_attachments, :attachment_id
add_index :inspected_event_attachments, :inspected_event_id
add_index :inspected_event_dates, :created_by_id
add_index :inspected_event_dates, :inspected_event_id
add_index :inspected_event_dates, :organization_id
add_index :inspected_event_dates, :updated_by_id
add_index :inspected_events, :billed_by_id
add_index :inspected_events, :created_by_id
add_index :inspected_events, :organization_id
add_index :inspected_events, :replaced_inspector_id
add_index :inspected_events, :updated_by_id
add_index :inspected_events, :venue_id
add_index :inspection_attachments, :attachment_id
add_index :inspection_attachments, :inspection_id
add_index :inspections, :accounting_approved_by_id
add_index :inspections, :admin_approved_by_id
add_index :inspections, :billed_by_id
add_index :inspections, :created_by_id
add_index :inspections, :inspected_event_date_id
add_index :inspections, :inspector_id
add_index :inspections, :kashruth_admin_approved_by_id
add_index :inspections, :organization_id
add_index :inspections, :paid_by_id
add_index :inspections, :rc_approved_by_id
add_index :inspections, :submitted_by_id
add_index :inspections, :updated_by_id
add_index :inspector_assignments, :inspector_id
add_index :inspector_assignments, :organization_id
add_index :issue_attachments, :attachment_id
add_index :issue_attachments, :issue_id
add_index :issues, :created_by_id
add_index :issues, :detected_by_id
add_index :issues, :ingredient_id
add_index :issues, :inspection_id
add_index :issues, :organization_id
add_index :issues, :product_id
add_index :issues, :resolved_by_id
add_index :issues, :updated_by_id
add_index :notebooks, :company_id
add_index :notes, :created_by_id
add_index :notes, :notebook_id
add_index :organization_attachments, :attachment_id
add_index :organization_attachments, :organization_id
add_index :organization_categories, :created_by_id
add_index :organization_categories, :updated_by_id
add_index :organization_organization_categories, :organization_id
add_index :organization_params, :created_by_id
add_index :organization_params, :organization_id
add_index :organization_params, :updated_by_id
add_index :organizations, :account_manager_id
add_index :organizations, :address_id
add_index :organizations, :alternate_inspector_id
add_index :organizations, :company_id
add_index :organizations, :coordinator_id
add_index :organizations, :inspector_id
add_index :organizations, :reviewed_by_id
add_index :organizations, :telcom_id
add_index :params, :created_by_id
add_index :params, :updated_by_id
add_index :payments, :created_by_id
add_index :payments, :organization_id
add_index :payments, :paid_by_id
add_index :payments, :paypal_payer_id
add_index :payments, :updated_by_id
add_index :personalizations, :user_id
add_index :product_attachments, :attachment_id
add_index :product_attachments, :product_id
add_index :product_certification_letters, :certification_letter_id
add_index :product_certification_letters, :product_id
add_index :product_groups, :company_id
add_index :product_is_ingredients, :ingredient_id
add_index :product_is_ingredients, :product_id
add_index :product_plants, :plant_id
add_index :product_plants, :product_id
add_index :product_uses_ingredients, :ingredient_id
add_index :product_uses_ingredients, :product_id
add_index :production_lines, :plant_id
add_index :products, :brand_id
add_index :products, :certifier_id
add_index :products, :created_by_id
add_index :products, :previous_id
add_index :products, :previous_state_changed_by_id
add_index :products, :producer_id
add_index :products, :product_group_id
add_index :products, :production_line_id
add_index :products, :replaced_by_id
add_index :products, :state_changed_by_id
add_index :products, :ukd_id
add_index :products, :updated_by_id
add_index :report_templates, :created_by_id
add_index :report_templates, :updated_by_id
add_index :report_templates, :user_id
add_index :running_processes, :session_id
add_index :trucking_log_attachments, :attachment_id
add_index :trucking_log_attachments, :trucking_log_id
add_index :users, :contact_id
add_index :users, :created_by_id
add_index :users, :login, :unique => true
add_index :users, :updated_by_id
  end
end
